### ISSUE TITLE
Update docs to discuss streaming chat completions

### ISSUE THREAD

**Issue by cdbartholomew** [LangStream/documentation#77]
I couldn't find any documentation on streaming chat completions. For example, I search for the configuration `stream-to-topic` and didn't find anything in the docs.

We should add a section on how "streaming" from the chat completion works, since it is likely to be confused with data streaming. In this section, we should highlight how "streaming" completions are an ideal fit with an async framework like LangStream and that it is well supported by our WebSockets gateway.

We should also update the configuration reference information for ai-chat-completions.

**Comment by cdbartholomew** [comment]
@eolivelli Can you help with the content for this?

**Comment by eolivelli** [comment]
In the ai-chat-completion and in the ai-text-completion agents you can configure the "stream-to-topic" parameter.

In that case the agent starts writing to the "stream-to-topic" any tokes coming from the LLM.

In fact LLMs internally work "one token at a time" and with the native streaming capabilities of LangStream is it possible to leverage this behaviour.

There are two main configuration properties:
- stream-to-topic: this is the name of the topic
- stream-response-completion-field: this is the field to set in the records sent to the stream-to-topic topic

Usually the value for stream-response-completion-field is "value", that means that the token from the LLM replaces the whole content of the "value" part of the message and you can serve it with a gateway directly.

Even when you configure a "stream-to-topic" the regular output of the agent is the same as before, the message is emitted to the downstream agent (or output) when the whole sequence of tokens is received.

 In order to limit the number of writes to the broker the agent groups the token, it can create sequences of up to "min-chunks-per-message". The first token is sent as soon as possible, then 2, then 4, up to the limit.

**Comment by eolivelli** [comment]
The messages sent on the stream-to-topic are marked with special properties:

stream-id: this is a string, that is the id of the whole answer
stream-index: this is a number (as string) the index of the token in the sequence
stream-last-message: this is a boolean (as string, "true" or "false") that is "true" then the message is the last of the answer
