### ISSUE TITLE
Explain "when" configuration property for steps

### ISSUE THREAD

**Issue by nicoloboschi** [LangStream/documentation#83]
https://github.com/datastax/pulsar-transformations#expression-language

currently there's no clue about how to do it

**Comment by mendonk** [comment]
https://docs.langstream.ai/pipeline-agents/builtin-agents/data-transform/compute#conditional-steps

**Comment by eolivelli** [comment]
@mendonk I would move the expression language to a dedicate page, because now it is used by many agents, for instance it is used by the "query"/"query-vector-db" and by many (all except Cassandra/Astra) "vector-db-sink"s and we are using it in all the new agents (for instance Flare, Router, Http Request...)

**Comment by eolivelli** [comment]
created https://github.com/LangStream/documentation/issues/106
